# This file controls what config variables you want to be able to allow your users
# to set, as well as those you'll be able to access from within the application.
# 
# If you want to be able to access a string config[:site_title], for example:
#   
site_title:
  name: Site Title
  type: text
  default: EEK! (Easy Expense Keeper) App

total_budget:
  name: Total Budget
  type: float
  default: 0

allow_user_signup:
  name: Allow new user account creation
  type: boolean
  default: true
# 'name' is the name that appears in the edit form
# 
# 'type' can be 'string' for a text field, 'password' for a password field or 'text' for a text area
#   'type' defaults to 'string'
# 
# 'default' is the default value to use if there's no entry in the database. Otherwise, nil will be returned
# 
# Some Examples:
#   
# site_title:
#   name: Site Title
#   default: My Site
#   type: string
#   
# site_description:
#   name: Description for Google
#   default: Lots of Awesomeness Here
#   type: text
#   
# secret:
#   name: Secret Password for Accessing Secret Areas
#   default: secret
#   type: password
